name: deploy

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v5
        env: 
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        with:
          script: |
            const script = require('./release.js')
            await script({ github, context, require })
