name: deploy

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        id: get-release
        with:
          script: |
            const release = github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: context.payload.release.tag_name
            })
            console.log(release)
            return release
      - run: echo "${{ steps.get-release.outputs.result }}"
